### ISSUE TITLE
Util is not defined on datatype validation

### ISSUE THREAD

**Issue by Slaknoah** [cockroachdb/sequelize-cockroachdb#130]
Package returns this error when validating datatype
`ReferenceError: util is not defined
    at INTEGER.stringify (.../node_modules/sequelize-cockroachdb/source/index.js:89:9)
    at INTEGER.stringify (.../node_modules/sequelize/lib/data-types.js:24:19)
    at PostgresQueryGenerator.escape (.../node_modules/sequelize/lib/dialects/abstract/query-generator.js:985:30)`

Looking at the index.js , it file turns out the util package that was used for formatting here 
`if (!/^[-+]?[0-9]+$/.test(rep)) {
      throw new Sequelize.ValidationError(
        util.format('%j is not a valid integer', value)
      );
    }`
was not imported. Please look into it.

**Comment by rafiss** [comment]
@Slaknoah Thanks for reporting this! 

I've created https://github.com/cockroachdb/sequelize-cockroachdb/pull/131 to fix it
