### ISSUE TITLE
casting on ARRAY dataType

### ISSUE THREAD

**Issue by spondbob** [cockroachdb/sequelize-cockroachdb#20]
Create table:
```
var Bar = sequelize.define('bar', {
  array: Sequelize.ARRAY(Sequelize.STRING)
})
```
Produce:
```
CREATE TABLE bars (
	id INT NOT NULL DEFAULT unique_rowid(),
	"array" STRING[] NULL,
	"createdAt" TIMESTAMP WITH TIME ZONE NOT NULL,
	"updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL,
	CONSTRAINT "primary" PRIMARY KEY (id ASC),
	FAMILY "primary" (id, "array", "createdAt", "updatedAt")
)
```
Query:
```
Bar
  .create({ array: ['Item 1'] })
  .then(r => console.log(r))
  .catch(e => console.error(e))
```
Error:
```
Executing (default): INSERT INTO "bars" ("id","array","createdAt","updatedAt") VALUES (DEFAULT,ARRAY['Item 1']::VARCHAR(255)[],'2017-10-28 03:24:39.598 +00:00','2017-10-28 03:24:39.598 +00:00') RETURNING *;
Executing (default): SELECT i.relname AS name, ix.indisprimary AS primary, ix.indisunique AS unique, ix.indkey AS indkey, array_agg(a.attnum) as column_indexes, array_agg(a.attname) AS column_names, pg_get_indexdef(ix.indexrelid) AS definition FROM pg_class t, pg_class i, pg_index ix, pg_attribute a WHERE t.oid = ix.indrelid AND i.oid = ix.indexrelid AND a.attrelid = t.oid AND t.relkind = 'r' and t.relname = 'bars' GROUP BY i.relname, ix.indexrelid, ix.indisprimary, ix.indisunique, ix.indkey ORDER BY i.relname;
{ SequelizeDatabaseError: invalid cast: string[] -> VARCHAR(255)[]
    at Query.formatError (/home/Projects/test-api/node_modules/sequelize/lib/dialects/postgres/query.js:338:16)
    at query.catch.err (/home/Projects/test-api/node_modules/sequelize/lib/dialects/postgres/query.js:86:18)
    at tryCatcher (/home/Projects/test-api/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/Projects/test-api/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/home/Projects/test-api/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/home/Projects/test-api/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/Projects/test-api/node_modules/bluebird/js/release/promise.js:689:18)
    at Async._drainQueue (/home/Projects/test-api/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/home/Projects/test-api/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/home/Projects/test-api/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5)
  name: 'SequelizeDatabaseError',
  parent: 
   { error: invalid cast: string[] -> VARCHAR(255)[]
    at Connection.parseE (/home/Projects/test-api/node_modules/pg/lib/connection.js:567:11)
    at Connection.parseMessage (/home/Projects/test-api/node_modules/pg/lib/connection.js:391:17)
    at Socket.<anonymous> (/home/Projects/test-api/node_modules/pg/lib/connection.js:129:22)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at addChunk (_stream_readable.js:266:12)
    at readableAddChunk (_stream_readable.js:253:11)
    at Socket.Readable.push (_stream_readable.js:211:10)
    at TCP.onread (net.js:587:20)
     name: 'error',
     length: 115,
     severity: 'ERROR',
     code: '42846',
     detail: undefined,
     hint: undefined,
     position: undefined,
     internalPosition: undefined,
     internalQuery: undefined,
     where: undefined,
     schema: undefined,
     table: undefined,
     column: undefined,
     dataType: undefined,
     constraint: undefined,
     file: 'sql/parser/type_check.go',
     line: '268',
     routine: '(*CastExpr).TypeCheck',
     sql: 'INSERT INTO "bars" ("id","array","createdAt","updatedAt") VALUES (DEFAULT,ARRAY[\'Item 1\']::VARCHAR(255)[],\'2017-10-28 03:24:39.598 +00:00\',\'2017-10-28 03:24:39.598 +00:00\') RETURNING *;' },
  original: 
   { error: invalid cast: string[] -> VARCHAR(255)[]
    at Connection.parseE (/home/Projects/test-api/node_modules/pg/lib/connection.js:567:11)
    at Connection.parseMessage (/home/Projects/test-api/node_modules/pg/lib/connection.js:391:17)
    at Socket.<anonymous> (/home/Projects/test-api/node_modules/pg/lib/connection.js:129:22)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at addChunk (_stream_readable.js:266:12)
    at readableAddChunk (_stream_readable.js:253:11)
    at Socket.Readable.push (_stream_readable.js:211:10)
    at TCP.onread (net.js:587:20)
     name: 'error',
     length: 115,
     severity: 'ERROR',
     code: '42846',
     detail: undefined,
     hint: undefined,
     position: undefined,
     internalPosition: undefined,
     internalQuery: undefined,
     where: undefined,
     schema: undefined,
     table: undefined,
     column: undefined,
     dataType: undefined,
     constraint: undefined,
     file: 'sql/parser/type_check.go',
     line: '268',
     routine: '(*CastExpr).TypeCheck',
     sql: 'INSERT INTO "bars" ("id","array","createdAt","updatedAt") VALUES (DEFAULT,ARRAY[\'Item 1\']::VARCHAR(255)[],\'2017-10-28 03:24:39.598 +00:00\',\'2017-10-28 03:24:39.598 +00:00\') RETURNING *;' },
  sql: 'INSERT INTO "bars" ("id","array","createdAt","updatedAt") VALUES (DEFAULT,ARRAY[\'Item 1\']::VARCHAR(255)[],\'2017-10-28 03:24:39.598 +00:00\',\'2017-10-28 03:24:39.598 +00:00\') RETURNING *;' }
```
I think the problem here is cockroach does not accept casting when inserting an array `::VARCHAR(255)[]`. Removing the casting works well in db shell.

If we have a look ARRAY data types for postgres in Sequelize package, [this line](https://github.com/sequelize/sequelize/blob/master/lib/dialects/postgres/data-types.js#L577) adds the casting. Does recreate the `BaseTypes.ARRAY` without that line to this package will be the approach?

**Comment by justinj** [comment]
Hey @spondbob, sorry for the delay in getting back to you - I think this will be fixed in the upcoming (2.0) release of CockroachDB, could you try against one of our recent betas to see if this is fixed for you?

**Comment by spondbob** [comment]
Sure I'll try it soon. I am still working on another project, will come back here once I am able to spare a time. Thanks for having a look the issue.

**Comment by kidandcat** [comment]
I tried it and it's working now

**Comment by spondbob** [comment]
Sorry a bit late to this, adding @kidandcat I can confirm it is working now. See [here](https://github.com/spondbob/sequelize-cockroach-array)
